environment:
  PATH: '%PATH%;C:\Program Files (x86)\Rust\bin;C:\MinGW\bin'
platform:
  - x64
install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-nightly-x86_64-pc-windows-msvc.exe"
  - rust-nightly-x86_64-pc-windows-msvc.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - rustc --version
  - cargo --version

build: false

test_script:
  - 'cargo test --verbose --release'
